---
name: "pre-release"

on:
  push:
    branches:
      - "develop"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'
      - run: yarn
      - run: cd ./packages/webapp && yarn build:monocle && yarn build:alienfence
        env:
          NODE_ENV: production
      - uses: actions/upload-artifact@v2
        with:
          name: build-monocle
          path: ./packages/webapp/dist/monocle
      - uses: actions/upload-artifact@v2
        with:
          name: build-alienfence
          path: ./packages/webapp/dist/alienfence
